### ISSUE TITLE
Semantic Issue while building the POD project

### ISSUE THREAD

**Issue by anooj1483** [reactor-studio/react-native-zoom-sdk#1] opened 2018-04-03 17:54 UTC
![screen shot 2018-04-03 at 11 21 48 pm](https://user-images.githubusercontent.com/6260395/38266301-f0292758-3795-11e8-8647-1b9398e5ebf0.png)
Used `pod 'ZoomMobileRTC'`
Initially tried linking via `react-native link`, but it keeps on failing.

So I manually linked the node_module. But I'm getting semantic issues.

Also, there is red color in Frameworks folder in Libraries section.
![screen shot 2018-04-03 at 11 28 47 pm](https://user-images.githubusercontent.com/6260395/38266663-e225354c-3796-11e8-8d81-6086fb4500bf.png)

I've imported libRNMobileRTC.a to Link Binary With Libraries

![screen shot 2018-04-04 at 3 31 27 pm](https://user-images.githubusercontent.com/6260395/38301516-641375ec-381d-11e8-969f-2aa4aaf7b2bd.png)

**Comment by SoHotSoup** [comment] 2018-04-04 09:46
Hey @anooj1483! Thank you for submitting the issue. It seems you haven't initialized `git lfs` in your project. Be sure to use right version of `ZoomMobileRTC`, here is how that looks in our `Podfile`:

```
pod 'ZoomMobileRTC', '~> 2.0.2'
```

The problem is with Zoom SDK itself, it contains files bigger than 50 MB, so every git hosting requires to use `git lfs` to store it. To have that done, try this:

- Follow installation instructions: https://github.com/git-lfs/git-lfs/wiki/Installation
- Clean your CocoaPods cache by `rm -rf ~/Library/Caches/CocoaPods/`
- go to your repo directory and run `git lfs install`
- `cd ios`
- `pod install`

Please close the issue if everything is right...

**Closed** 2018-04-04 17:58 UTC
